import {
	type LucideIcon,
	Target,
	Clock,
	Database,
	Layers,
	Smile,
	Calendar,
	Users,
	Shield,
	Component,
	Layout,
	Gauge,
	Zap,
	ScanText,
	Brain,
	Sparkles,
	Route,
	Image as ImageIcon,
	UserCheck,
	ShieldCheck,
	MessageCircle,
	Headphones,
	CreditCard,
	LayoutDashboard,
	Utensils,
	ClipboardList,
	Grid3x3,
	Package,
	BarChart3,
	TrendingUp,
	Star,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
	target: Target,
	clock: Clock,
	database: Database,
	layers: Layers,
	smile: Smile,
	calendar: Calendar,
	users: Users,
	shield: Shield,
	component: Component,
	layout: Layout,
	gauge: Gauge,
	zap: Zap,
	"scan-text": ScanText,
	brain: Brain,
	sparkles: Sparkles,
	route: Route,
	image: ImageIcon,
	"user-check": UserCheck,
	"shield-check": ShieldCheck,
	"message-circle": MessageCircle,
	headphones: Headphones,
	"credit-card": CreditCard,
	"layout-dashboard": LayoutDashboard,
	utensils: Utensils,
	"clipboard-list": ClipboardList,
	grid: Grid3x3,
	package: Package,
	"bar-chart": BarChart3,
	"trending-up": TrendingUp,
	star: Star,
};

/** Resolve a lucide icon by name, falling back to a neutral default. */
export function getIcon(name?: string): LucideIcon {
	return (name && ICONS[name]) || Sparkles;
}
